### ISSUE TITLE
the decoding code

### ISSUE THREAD

**Issue by Ma-Yongqiang** [dilab-zju/self-speculative-decoding#1]
very interesting work! Could you please release the source code?

**Comment by junzhang-zj** [comment]
@Ma-Yongqiang Our code is in the process of being organized, and we will be perfecting it in the near future.

**Comment by felix-ky** [comment]
looking forward to your release

**Comment by caiyuhu** [comment]
looking forward to your release

**Comment by junzhang-zj** [comment]
@felix-ky @caiyuhu Thanks for your interest in our work, we will launch our first version in about 10 days.

**Comment by junzhang-zj** [comment]
We have updated our code.
