### ISSUE TITLE
Code for Llama-7b and Mistral

### ISSUE THREAD

**Issue by DRXD1000** [dilab-zju/self-speculative-decoding#11]
Hey guys, amazing work!

is there an easy way to update your code to use it on mistral or llama-2-7b-chat-hf?

I tried llama-2 but it did not work. 

Thanks!

**Comment by junzhang-zj** [comment]
The current code is adapted to llama-2-7b-chat-hf. You should first generate the corresponding draft model based on search.ipynb, and then use evaluate_sum.ipynb to evaluate it.
