### ISSUE TITLE
questions about Llama2-70b

### ISSUE THREAD

**Issue by xinlong-yang** [dilab-zju/self-speculative-decoding#13]
hi, thanks for your great work! In your paper, you said you use 2 A100 GPUs and hf accelerate to evaluate Llama2-70b, I want to know you just use original accelerate or use accelerate + deepspeed? Since your repo has no content about this, so I'm a little confused, thanks for your patience!

**Comment by junzhang-zj** [comment]
We only used device_map='auto' of accelerate to load model parameters, and did not use it and deepspeed to accelerate.

**Comment by xinlong-yang** [comment]
ok, fine, i got it, thanks!
