### ISSUE TITLE
Question about self-speculative + greedy decoding

### ISSUE THREAD

**Issue by egangu** [dilab-zju/self-speculative-decoding#16]
To the best of my knowledge, speculative decoding does not change the decoding result when using greedy decoding. However, I noticed that the rouge2 metrics of 'base' and 'essg' may be different in this repo. Although the gap is tiny, I still want to know what causes this difference in decoding.

**Comment by junzhang-zj** [comment]
We attribute any slight differences observed in the case of greedy decoding to numerical rounding errors.

**Comment by egangu** [comment]
> We attribute any slight differences observed in the case of greedy decoding to numerical rounding errors.

Thanks for your reply. This explanation is consistent with my exp.
