### ISSUE TITLE
Reject Sampling & Adaptive Draft-Exiting Mechanism

### ISSUE THREAD

**Issue by wutong4012** [dilab-zju/self-speculative-decoding#19]
Very interesting work, thank you for your contribution to the open source community.

1. In the first two papers, verification is done by probability rejection sampling, but I saw that the implementation of the code directly compares the generated ids. Are these two equivalent?
![image](https://github.com/user-attachments/assets/73ba0794-2c92-4cd8-b569-9dbb5ab47070)
![image](https://github.com/user-attachments/assets/41912693-3bdb-4a76-bee8-4c6b81cedffc)
https://github.com/dilab-zju/self-speculative-decoding/blob/6c719da65ada6a4cd99ea32e84030caa9aae22c0/decoding.py#L137

2. I saw the design of Adaptive Draft-Exiting Mechanism. What is the reason for this design? I did not find any relevant theoretical proof or intuitive explanation.
![image](https://github.com/user-attachments/assets/5cbcf953-e551-4cbd-a882-a287fdaa386c)

Please correct me if I'm wrong, thanks.

**Comment by junzhang-zj** [comment]
@wutong4012 In the greedy setting, this is equivalent, in the sampling setting, you can call sss, https://github.com/dilab-zju/self-speculative-decoding/blob/6c719da65ada6a4cd99ea32e84030caa9aae22c0/decoding.py#L190
As for the adaptive exit mechanism, I think Section 3.4 of the article has already explained it intuitively. It mainly uses the acceptance rate as an anchor point to judge the difficulty of the token, preventing the draft model from predicting difficult tokens that are destined to fail verification. Similarly, let simple tokens be generated by the draft model as much as possible.
