### ISSUE TITLE
Can you share your prompt of LLaMA-2-70B?

### ISSUE THREAD

**Issue by jaemin-han** [dilab-zju/self-speculative-decoding#3]
I would like to conduct an Autoregressive baseline experiment using the LLaMA-2-70B model on the CNN/DM dataset. However, I am unsure about the appropriate prompt to ensure accurate model inference. Could you kindly share the prompt you recommend for LLaMA-2-70B?

what I tried:
1. summary: [text want to summarize]
2. \[text summarization\]: \[text text want to summarize\]
3. Write a concise summary of the text, return your responses with 5 lines that cover the key points of the text.
    [text want to summarize]
    SUMMARY:
4. System: You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.  Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature. If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.  
[text want to summarize] 
summary:

**Comment by junzhang-zj** [comment]
We have updated the code and you can refer to it.

**Comment by jaemin-han** [comment]
Great! Thanks for the update! I'll take a look at the new code

2023년 10월 17일 (화) 오후 2:00, Jun Zhang ***@***.***>님이 작성:
