### ISSUE TITLE
question about the training data for bayesian and model size

### ISSUE THREAD

**Issue by irasin** [dilab-zju/self-speculative-decoding#9]
Great works!
I have some questions about the Bayesian optimization and performance on the small model size:

1. The paper says that you use XSum and CNN/DM data for bayesian. I was wondering if I have a new llama-based fined-tuned model or some other open-source models trained with different source data, e.g. (baichuan/Qwen/chatglm etc.), should I use some specfic data to train for bayesian?
2. What is the result of 7B size model like llama7B/llama2-7B?

Hope to get answer. Thanks a lot.

**Comment by irasin** [comment]
Also, I was wondering if I change the dataset for bayesian on the same model, let say XSum data on llama2-13B and some other custom data on llama13B, will the skip-layers be different in this two cases?

**Comment by junzhang-zj** [comment]
Thank you for your appreciation of our work.
For the BO data set settings, if the tasks to be tested are very different, we recommend searching at the task level, so the skip layers of different datasets may be different;
We have no plans to experiment on the 7B model yet, but the redundancy of their pairs may be smaller.
